sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: M9xmfDa1HVfLCiql1zITVALFTkoTbmK3/+1S3QJTVVM4nKuZ2wAMe6InR9yfj4DXS3PfwwnaeoTE5kGvvt+2le9EvjRzcP8qCbAO+8U3IK9nw4Dsbt82KhyoO1ciGQF/IqcSEDhuL8SDy1EJKasS39l4iiJhAyOujU8huaxwObYs/DyIEsHlE8ibEpaLXoHeBWYZT7FcWRoYr+0nlkCSxz2jYpg7NhlsiRpMwOmAfXE/3TMY9hhpZU+6No1gAPyxX2e9V9iCJnHvyjb+xq7tSftIQoA0S2nr2dycEbXbImYuHkx2PI+g2yLBMJuh0ysBZu0Kc1S0Y2/GfCnrtwQF6DDaWiX/pDKjiPrMGSfz/jm/i8Xl1Aaqx/+akJhVxwVF8uTRVPoxZwjGhcflZBO42aWqJJPEXlXYjv3arC7bhcuAmZynsnqvZnK3Gj8/YqgifMWnOXyw6sbeR8cTCGzpq0f2TzDiWUsVCAbBaYPp0wGVxug6ynrSFWDNLWzJ/lrNQbaJ2A4vVJkHGFpKJTCxBcwsVmBjPWCDx8im9OHrdO875TFMnBAO0G6CXjao/x1Q5iMG2WTVsZRtYPU4xgyP4xZqYtqiGAtGJ3W7U6J16ieMVDOzPGh8ngUCz7RnmxONQH5qV+yQWZHvaTaP8JRYQviu2q94haGzxVDLqp7kg8Q=
    - secure: NolEe2do7UzpSpTu6t2yESzEV/WGspvMXTJv84kHcklQqISnQJtvb+40IBi1gjFPCgO/PH70651b3p3/J5USlCyb1f2ONNTcUxjZ6mU5sJBWFtuFAZWbGTAQiG2d8Trs5d4ZoKF3MyDMvCid6rKGkDoqmomOLgyHHrrfHJZsjecSmnaQwtAVOhkYhj5Yj5BaoxAPFKrnvFeTi9LZlIxaI8ZCk+anKgjAUdrwbCJ6iSDL0PdXXWQPCkhdkgXcUerXPFXGi8YKI82nmmqK1VL3fqhSWjPxV9nXdlvwfoDBglSW6R4/ZsafeTZbZ26SQ3ecQl/tnLS23QywBIWI0F9QiwPMuPgif7f6RiFy4arHUkhDb5TbQgM0XjQ2lKKBY7IwNCPUQOEzUK7w9glQMoLaLOfZTFf0C/j7bxZTgjMse39EUZX3MfrEmCPtswGUyq5GefvlNmHuOeqPShXolz2oldNA8r1axqGK9hCqqVXZ/EwCmXOZkoGBshBLFND0Qzhec+Qb6FzHClibwbkUkkGlaOUUHqU700Q9X9An+WvJ+XzkCJSo+MseLgA4waRCKIy2ZOn0/5Tn+Oz5Zz/T5g13rU3rQcBpEbMe6xNSoMJ4p5Du9XYlrrZW/Vv40pc4Xe8HgtIRvdeSjY+3F1gGh64CpiKBtF0MAqYFgf5Pv7vAb4o=
